### ISSUE TITLE
Usage of steam profile

### ISSUE THREAD

**Issue by Elinvention** [mk-fg/apparmor-profiles#3]
Your steam profile confines the steam executable located in `/usr/bin/steam`. I'm using Debian and I'm a bit confused where to look for the actual executable. I tried to name it `usr.games.steam`, but when I started steam, with `aa-status` I saw that the profile was in enforce mode, but not the process.

It seems that the actual steam binary is located in `~/.steam/ubuntu12_32/steam`. Should I change the profile to match that?

Thank you.

**Comment by Elinvention** [comment]
I solved my problem. `/usr/games/steam` was correct by I had to reload apparmor profiles.

Thank you for this profiles!

**Comment by mk-fg** [comment]
Filename, e.g. `usr.bin.steam` doesn't actually mean anything to apparmor_parser - you can simply name it "steam", "whatever" or pipe the file to apparmor_parser's stdin and it should work exactly the same.

What determines which profile gets activated for executable (aside from transition rules from other profiles) is "attachment specification" - `/usr/bin/steam {` line there.
See AppArmor wiki for more details: http://wiki.apparmor.net/index.php/AppArmor_Core_Policy_Reference#Profile_names_and_attachment_specifications

I haven't used steam for years now, but from what I remember about how it worked here, it has a bootstrap-wrapper which I've installed as OS package (and that has `/usr/bin/steam` binary) which either downloads and sets up steam client and chroot for user that runs it or simply runs/re-uses existing client setup, if it was done already (i.e. you've run it before).

`owner @{HOME}/** rwkmixl,` line takes care of that hand-off, i.e. anything in ~ can be read/written-to and run.
Which I have there with a `# Should always have dedicated uid and home` comment because I had separate uid for steam, i.e. it has its own user and home-dir, which it can use freely, and don't need any extra limits there.

I recall summing all that setup up in a blog post a while ago:
http://blog.fraggod.net/2014/06/15/running-isolated-steam-instance-with-its-own-uid-and-session.html
No idea how relevant it is by now though, as steam client might've changed a lot since then.

**Comment by mk-fg** [comment]
Apparently wrote last comment at the same time as you did.
Glad it was resolved. Cheers!
